### ISSUE TITLE
Keylogging question

### ISSUE THREAD

**Issue by jaylawl** [ASangarin/AriKeys#4]
Fantastic idea! I'm excited to play around with this and potentially implement it into my stuff.

But, important question that came to me: In which "player states" are the key presses sent?

Are they sent only while the game window is focused?
Are they sent while the player has an inventory open?
... while the player is typing in chat?

Cheers

/edit:
Just to clarify: The nature of this question comes from the fact that, if i were to use this, i would also promote the everliving shit out of it. That's why i'm inclined making sure it is safe to use for clients

**Comment by ASangarin** [comment]
Sorry for the **_late_** reply.
The key presses are only sent when the player is "controlling their character".
So yeah, no presses are sent if the player is currently viewing any GUI (including chat).

Hope that answers your question :)

**Comment by jaylawl** [comment]
Sure did! And better late than never :-) Thanks.

Followup question: In which manner are the key presses transmitted? I would assume it to be:
- Player presses key "G"
- Client mod detects "G" to be "hotkey 1"
- Client mod sends information that "hotkey 1" was pressed to server

Or is it literally:
- Client mod sends information that key "G" was pressed?

Thanks again.

Oh and why did you rename the plugin?

**Comment by ASangarin** [comment]
You're correct, it only sends registered keybinds to the server.
There's a feature that allows you to "flag" the vanilla keybinds so that the client can send those to the server as well.

I renamed the plugin to better fit future mod/plugin projects like this one.
Originally it was intended to be yet another "MythicSuite" plugin, but I had a second thought and the mod/plugin itself doesn't feel like a true Mythic plugin, but rather something unique.
I'll be releasing future plugins like this, so prefixing them all with "Ari" then something related to the core mechanics of it was the way to go imo.

Hope that helps :)

**Comment by jaylawl** [comment]
Thanks homie!
